<a href="https://colab.research.google.com/github/AkashDulange/Akash/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3], dtype=np.int32)
print(a)

[1 2 3]


In [ ]:
b=np.array([[7.2,8.3,9.3],[3.8,2.5,3.7]])
print(b)


[[7.2 8.3 9.3]
 [3.8 2.5 3.7]]


In [ ]:
#Get Dimension
b.ndim
a.ndim

1

In [ ]:
#Get Type
a.dtype
# b.dtype

dtype('int32')

In [ ]:
#Get Size
a.itemsize

4

In [ ]:
#Get Size
a.nbytes

24

In [ ]:
c=np.arange(1,25).reshape(4,6)
print(c)
print()
d=np.arange(50,74).reshape(4,6)
print(d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

[[50 51 52 53 54 55]
 [56 57 58 59 60 61]
 [62 63 64 65 66 67]
 [68 69 70 71 72 73]]


In [ ]:
#Get a specific element
#c[1,5]
c[3,3]

22

In [ ]:
#Get a specific row
c[3,:]

array([19, 20, 21, 22, 23, 24])

In [ ]:
#Get a specific column
c[:,2]

array([ 3,  9, 15, 21])

In [ ]:
#Addition of 2 arrays
sum=c+d
print(sum)


[[51 53 55 57 59 61]
 [63 65 67 69 71 73]
 [75 77 79 81 83 85]
 [87 89 91 93 95 97]]


In [ ]:
#Substraction of 2 arrays
sub=d-c
print(sub)

[[49 49 49 49 49 49]
 [49 49 49 49 49 49]
 [49 49 49 49 49 49]
 [49 49 49 49 49 49]]


In [ ]:
#Multiplication of 2 arrays(ElementWise)
mul=c * d
print(mul)

[[  50  102  156  212  270  330]
 [ 392  456  522  590  660  732]
 [ 806  882  960 1040 1122 1206]
 [1292 1380 1470 1562 1656 1752]]


In [ ]:
#Multiplication of 2 arrays(matrix prod)
a1=np.arange(1,26).reshape(5,5)
print(a1)
a2=np.arange(26,51).reshape(5,5)
print(a2)
a1@a2



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


array([[ 590,  605,  620,  635,  650],
       [1490, 1530, 1570, 1610, 1650],
       [2390, 2455, 2520, 2585, 2650],
       [3290, 3380, 3470, 3560, 3650],
       [4190, 4305, 4420, 4535, 4650]])

In [ ]:
a1.dot(a2)

array([[ 590,  605,  620,  635,  650],
       [1490, 1530, 1570, 1610, 1650],
       [2390, 2455, 2520, 2585, 2650],
       [3290, 3380, 3470, 3560, 3650],
       [4190, 4305, 4420, 4535, 4650]])

In [ ]:
#3D Array
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#Creating an array full of Zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#Creating an array full of ones
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
#Unary Operations
a=np.random.random((2,3))
print(a)

#Sum
a.sum()
#Maximum
a.max()
#Minimum
a.min()

[[0.46898264 0.14186025 0.8545178 ]
 [0.27083461 0.16552938 0.4575108 ]]


0.1418602532794706

In [ ]:
#Universal Functions
B=np.arange(3)
print(B)

np.exp(B)

np.sqrt(B)

C=np.array((2., -1., 4.))
np.add(B,C)

[0 1 2]


array([2., 0., 6.])

[0.88287487 0.07944693 0.77755864 0.60369985 0.82235027]
